# SQL Interview Questions  - Quiz

## Introduction

In this lesson, we'll go through a short quiz containing the types of questions about SQL and relational databases that you can expect to see in an interview. 



## SQL Interview Questions

This quiz contains questions on topics you can expect to see in an interview pertaining to SQL and Relational Databases. Some of them are multiple choice, while some are short answer. For these short answer questions, double click on the Jupyter Notebook and type your answer below the line. 

## Question 1

what are the 4 main datatypes in SQLite3? Can we use other common types from other kinds of SQL?

Type your answer below this line:
_______________________________________________________________________________________________________________________________

The four types are:
* integer
* text
* real
* blob

Yes, we can use other common datatypes from other types of SQL. These SQLite3 datatypes are categories, and will classify similar types into one of the four. 




## Question 2

Explain the relationship between **Primary Keys** and **Foreign Keys**.

Type your answer below this line:
_______________________________________________________________________________________________________________________________

Primay keys are index for a specific record table within a database, and are unique within that table. Foreign keys are keys that may refer to primay keys in a field in another table.



## Question 3

Explain the different types of relationships entities can have in a SQL database. 

Type your answer below this line:
_______________________________________________________________________________________________________________________________

There are one-to-one, one-to-many, and many-to-many relationships in SQL. One-to-one refers to direct relationships between a record in one table and a record in another table, of which is the only realtionship those records have. One-to-many reffers to situations where one record may connect to many other records in another table, where the primary key in one record may be the foreign key for multiple records in a corresponding table. 

A many to many realtionship refers to a complex relationship where many records may correspond with many others. 

## Question 4

Explain the various types of JOINs possible with SQL. 

Type your answer below this line:
_______________________________________________________________________________________________________________________________

Inner - select all records from both tables where the join condition is met
Left - select all records from table A, along with records from table B where join conditions are met
Right - select all records from table B, along with records from table A where join conditions are met
Outer - select only records from all tables where there is no match on join conditions



## Question 5

Explain the relationship between Aggregate functions and GROUP BY statements.

Type your answer below this line:
_______________________________________________________________________________________________________________________________

In order for aggregate functions to work well, they need to know which groups of data they are considering to do their calculations. For example, if we wanted to know the total number of customers by state, we would need to group our data by state, and then sum or count the customers. 



## Question 6

What role do Associative Entities play (JOIN Tables) in many-to-many JOINs?


Type your answer below this line:
_______________________________________________________________________________________________________________________________

Associative entities make many-to-many joins possible by logging the different associations between two separate entities. They crate a new value to catalogue those associations, which otherwise would be impossible as direct one-to-one or one-to-many joins. 


## Summary

In this lesson, we practiced answering open-ended interview questions for SQL and Relational Databases.